version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: dockerHub-username
    DOCKERHUB_PASSWORD: /myapp/docker-credentials/password
    #Systems Manager: Parameter Store -> create parameter
    #name:dockerHub-username, type:SecureString, Value:<username>
    #name:dockerHub-password, type:SecureString, Value:<password

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Docker Hub..
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_NAME .
      
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_NAME

